package net.aerith.misao.xml.relaxer;

/**
 * PixyFactory is generated by Relaxer based on pixy.rlx.
 *
 * @version pixy.rlx (Tue Nov 23 20:34:02 JST 2004)
 * @author  Relaxer 0.10.1 (by ASAMI@Yokohama)
 */
public class PixyFactory {
    private static IPixyFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(IPixyFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return IPixyFactory
     */
    public static IPixyFactory getFactory() {
        if (factory == null) {
            factory = new DefaultPixyFactory();
        }
        return (factory);
    }
}
