package net.aerith.misao.xml.relaxer;

import org.w3c.dom.*;

/**
 * <b>XmlDistortionField</b> is generated by Relaxer based on pixy.rlx.
 * This class is derived from:
 * 
 * <!-- for programmer
 * <elementRule role="distortion-field">
 *   <sequence>
 *     <element name="x" type="string"/>
 *     <element name="y" type="string"/>
 *   </sequence>
 * </elementRule>
 * 
 * <tag name="distortion-field"/>
 * -->
 * <!-- for javadoc -->
 * <pre> &lt;elementRule role="distortion-field"&gt;
 *   &lt;sequence&gt;
 *     &lt;element name="x" type="string"/&gt;
 *     &lt;element name="y" type="string"/&gt;
 *   &lt;/sequence&gt;
 * &lt;/elementRule&gt;
 * &lt;tag name="distortion-field"/&gt;
 * </pre>
 *
 * @version pixy.rlx (Tue Nov 23 20:34:01 JST 2004)
 * @author  Relaxer 0.10.1 (by ASAMI@Yokohama)
 */
public class XmlDistortionField extends net.aerith.misao.xml.IONode implements java.io.Serializable, IRNode {
    private String x;
    private String y;
    private IRNode parentRNode;
    private RContext rContext;

    /**
     * Creates a <code>XmlDistortionField</code>.
     *
     */
    public XmlDistortionField() {
    }

    /**
     * Creates a <code>XmlDistortionField</code> by the Stack <code>stack</code>
     * that contains Elements.
     * This constructor is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     */
    public XmlDistortionField(RStack stack) {
        setup(stack);
    }

    /**
     * Creates a <code>XmlDistortionField</code> by the Document <code>doc</code>.
     *
     * @param doc
     */
    public XmlDistortionField(Document doc) {
        setup(doc.getDocumentElement());
    }

    /**
     * Creates a <code>XmlDistortionField</code> by the Element <code>element</code>.
     *
     * @param element
     */
    public XmlDistortionField(Element element) {
        setup(element);
    }

    /**
     * Initializes the <code>XmlDistortionField</code> by the Document <code>doc</code>.
     *
     * @param doc
     */
    public void setup(Document doc) {
        setup(doc.getDocumentElement());
    }

    /**
     * Initializes the <code>XmlDistortionField</code> by the Element <code>element</code>.
     *
     * @param element
     */
    public void setup(Element element) {
        init(element);
    }

    /**
     * Initializes the <code>XmlDistortionField</code> by the Stack <code>stack</code>
     * that contains Elements.
     * This constructor is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     */
    public void setup(RStack stack) {
        setup(stack.popElement());
    }

    /**
     * @param element
     */
    private void init(Element element) {
        IPixyFactory factory = PixyFactory.getFactory();
        RStack stack = new RStack(element);
        x = URelaxer.getElementPropertyAsString(stack.popElement());
        y = URelaxer.getElementPropertyAsString(stack.popElement());
    }

    /**
     * Creates a DOM representation of the object.
     * Result is appended to the Node <code>parent</code>.
     *
     * @param parent
     */
    public void makeElement(Node parent) {
        Document doc;
        if (parent instanceof Document) {
            doc = (Document)parent;
        } else {
            doc = parent.getOwnerDocument();
        }
        Element element = doc.createElement("distortion-field");
        int size;
        URelaxer.setElementPropertyByString(element, "x", x);
        URelaxer.setElementPropertyByString(element, "y", y);
        parent.appendChild(element);
    }

    /**
     * Gets the String property <b>x</b>.
     *
     * @return String
     */
    public final String getX() {
        return (x);
    }

    /**
     * Sets the String property <b>x</b>.
     *
     * @param x
     */
    public final void setX(String x) {
        this.x = x;
    }

    /**
     * Gets the String property <b>y</b>.
     *
     * @return String
     */
    public final String getY() {
        return (y);
    }

    /**
     * Sets the String property <b>y</b>.
     *
     * @param y
     */
    public final void setY(String y) {
        this.y = y;
    }

    /**
     * Gets the IRNode property <b>parentRNode</b>.
     *
     * @return IRNode
     */
    public final IRNode getParentRNode() {
        return (parentRNode);
    }

    /**
     * Sets the IRNode property <b>parentRNode</b>.
     *
     * @param parentRNode
     */
    public final void setParentRNode(IRNode parentRNode) {
        this.parentRNode = parentRNode;
    }

    /**
     * Gets child RNodes.
     *
     * @return IRNode[]
     */
    public IRNode[] getRNodes() {
        java.util.List classNodes = new java.util.ArrayList();
        IRNode[] nodes = new IRNode[classNodes.size()];
        return ((IRNode[])classNodes.toArray(nodes));
    }

    /**
     * Gets the RContext property <b>rContext</b>.
     *
     * @return RContext
     */
    public final RContext getRContext() {
        return (rContext);
    }

    /**
     * Sets the RContext property <b>rContext</b>.
     *
     * @param rContext
     */
    public final void setRContext(RContext rContext) {
        this.rContext = rContext;
        IRNode[] contextRNodes = getRNodes();
        for (int i = 0;i < contextRNodes.length;i++) {
            contextRNodes[i].setRContext(rContext);
        }
    }

    /**
     * Gets the property "rContext" which is resolved recursively.
     *
     * @return RContext
     */
    public RContext getRContextResolved() {
        if (rContext != null) {
            return (rContext);
        }
        if (parentRNode == null) {
            return (null);
        }
        return (parentRNode.getRContextResolved());
    }

    /**
     * Tests if a Element <code>element</code> is valid
     * for the <code>XmlDistortionField</code>.
     *
     * @param element
     * @return boolean
     */
    public static boolean isMatch(Element element) {
        String tagName = element.getTagName();
        if (!"distortion-field".equals(tagName)) {
            return (false);
        }
        RStack target = new RStack(element);
        Element child;
        child = target.popElement();
        if (child == null) {
            return (false);
        }
        if (!"x".equals(child.getTagName())) {
            return (false);
        }
        child = target.popElement();
        if (child == null) {
            return (false);
        }
        if (!"y".equals(child.getTagName())) {
            return (false);
        }
        if (!target.isEmptyElement()) {
            return (false);
        }
        return (true);
    }

    /**
     * Tests if elements contained in a Stack <code>stack</code>
     * is valid for the <code>XmlDistortionField</code>.
     * This mehtod is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     * @return boolean
     */
    public static boolean isMatch(RStack stack) {
        Element element = stack.peekElement();
        if (element == null) {
            return (false);
        }
        return (isMatch(element));
    }

    /**
     * Tests if elements contained in a Stack <code>stack</code>
     * is valid for the <code>XmlDistortionField</code>.
     * This method consumes the stack contents during matching operation.
     * This mehtod is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     * @return boolean
     */
    public static boolean isMatchHungry(RStack stack) {
        Element element = stack.peekElement();
        if (element == null) {
            return (false);
        }
        if (isMatch(element)) {
            stack.popElement();
            return (true);
        } else {
            return (false);
        }
    }
}
