package net.aerith.misao.xml.relaxer;

import org.w3c.dom.*;

/**
 * <b>XmlStar</b> is generated by Relaxer based on pixy.rlx.
 * This class is derived from:
 * 
 * <!-- for programmer
 * <elementRule role="star">
 *   <ref label="record" occurs="+"/>
 * </elementRule>
 * 
 * <tag name="star">
 *   <attribute name="name" required="true" type="ID"/>
 * </tag>
 * -->
 * <!-- for javadoc -->
 * <pre> &lt;elementRule role="star"&gt;
 *   &lt;ref label="record" occurs="+"/&gt;
 * &lt;/elementRule&gt;
 * &lt;tag name="star"&gt;
 *   &lt;attribute name="name" required="true" type="ID"/&gt;
 * &lt;/tag&gt;
 * </pre>
 *
 * @version pixy.rlx (Tue Nov 23 20:34:01 JST 2004)
 * @author  Relaxer 0.10.1 (by ASAMI@Yokohama)
 */
public class XmlStar extends net.aerith.misao.xml.IONode implements java.io.Serializable, IRNode {
    private String name;
    // List<XmlRecord>
    private java.util.List record = new java.util.ArrayList();
    private IRNode parentRNode;
    private RContext rContext;

    /**
     * Creates a <code>XmlStar</code>.
     *
     */
    public XmlStar() {
    }

    /**
     * Creates a <code>XmlStar</code> by the Stack <code>stack</code>
     * that contains Elements.
     * This constructor is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     */
    public XmlStar(RStack stack) {
        setup(stack);
    }

    /**
     * Creates a <code>XmlStar</code> by the Document <code>doc</code>.
     *
     * @param doc
     */
    public XmlStar(Document doc) {
        setup(doc.getDocumentElement());
    }

    /**
     * Creates a <code>XmlStar</code> by the Element <code>element</code>.
     *
     * @param element
     */
    public XmlStar(Element element) {
        setup(element);
    }

    /**
     * Initializes the <code>XmlStar</code> by the Document <code>doc</code>.
     *
     * @param doc
     */
    public void setup(Document doc) {
        setup(doc.getDocumentElement());
    }

    /**
     * Initializes the <code>XmlStar</code> by the Element <code>element</code>.
     *
     * @param element
     */
    public void setup(Element element) {
        init(element);
    }

    /**
     * Initializes the <code>XmlStar</code> by the Stack <code>stack</code>
     * that contains Elements.
     * This constructor is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     */
    public void setup(RStack stack) {
        setup(stack.popElement());
    }

    /**
     * @param element
     */
    private void init(Element element) {
        IPixyFactory factory = PixyFactory.getFactory();
        RStack stack = new RStack(element);
        name = URelaxer.getAttributePropertyAsString(element, "name");
        record.clear();
        while (!stack.isEmptyElement()) {
            if (XmlRecord.isMatch(stack)) {
                addRecord(factory.createXmlRecord(stack));
            } else {
                break;
            }
        }
    }

    /**
     * Creates a DOM representation of the object.
     * Result is appended to the Node <code>parent</code>.
     *
     * @param parent
     */
    public void makeElement(Node parent) {
        Document doc;
        if (parent instanceof Document) {
            doc = (Document)parent;
        } else {
            doc = parent.getOwnerDocument();
        }
        Element element = doc.createElement("star");
        int size;
        URelaxer.setAttributePropertyByString(element, "name", name);
        size = record.size();
        for (int i = 0;i < size;i++) {
            XmlRecord value = (XmlRecord)this.record.get(i);
            value.makeElement(element);
        }
        parent.appendChild(element);
    }

    /**
     * Gets the String property <b>name</b>.
     *
     * @return String
     */
    public final String getName() {
        return (name);
    }

    /**
     * Sets the String property <b>name</b>.
     *
     * @param name
     */
    public final void setName(String name) {
        this.name = name;
        if (rContext != null) {
            rContext.setIRNode(name, this);
        }
    }

    /**
     * Gets the XmlRecord property <b>record</b>.
     *
     * @return XmlRecord[]
     */
    public final XmlRecord[] getRecord() {
        IPixyFactory factory = PixyFactory.getFactory();
        XmlRecord[] array = factory.createArrayXmlRecord(record.size());
        return ((XmlRecord[])record.toArray(array));
    }

    /**
     * Sets the XmlRecord property <b>record</b>.
     *
     * @param record
     */
    public final void setRecord(XmlRecord[] record) {
        this.record.clear();
        this.record.addAll(java.util.Arrays.asList(record));
        for (int i = 0;i < record.length;i++) {
            record[i].setParentRNode(this);
        }
    }

    /**
     * Adds the XmlRecord property <b>record</b>.
     *
     * @param record
     */
    public final void addRecord(XmlRecord record) {
        this.record.add(record);
        record.setParentRNode(this);
    }

    /**
     * Gets the IRNode property <b>parentRNode</b>.
     *
     * @return IRNode
     */
    public final IRNode getParentRNode() {
        return (parentRNode);
    }

    /**
     * Sets the IRNode property <b>parentRNode</b>.
     *
     * @param parentRNode
     */
    public final void setParentRNode(IRNode parentRNode) {
        this.parentRNode = parentRNode;
    }

    /**
     * Gets child RNodes.
     *
     * @return IRNode[]
     */
    public IRNode[] getRNodes() {
        java.util.List classNodes = new java.util.ArrayList();
        classNodes.addAll(record);
        IRNode[] nodes = new IRNode[classNodes.size()];
        return ((IRNode[])classNodes.toArray(nodes));
    }

    /**
     * Gets the RContext property <b>rContext</b>.
     *
     * @return RContext
     */
    public final RContext getRContext() {
        return (rContext);
    }

    /**
     * Sets the RContext property <b>rContext</b>.
     *
     * @param rContext
     */
    public final void setRContext(RContext rContext) {
        this.rContext = rContext;
        IRNode[] contextRNodes = getRNodes();
        for (int i = 0;i < contextRNodes.length;i++) {
            contextRNodes[i].setRContext(rContext);
        }
        setName(getName());
    }

    /**
     * Gets the property "rContext" which is resolved recursively.
     *
     * @return RContext
     */
    public RContext getRContextResolved() {
        if (rContext != null) {
            return (rContext);
        }
        if (parentRNode == null) {
            return (null);
        }
        return (parentRNode.getRContextResolved());
    }

    /**
     * Tests if a Element <code>element</code> is valid
     * for the <code>XmlStar</code>.
     *
     * @param element
     * @return boolean
     */
    public static boolean isMatch(Element element) {
        String tagName = element.getTagName();
        if (!"star".equals(tagName)) {
            return (false);
        }
        RStack target = new RStack(element);
        Element child;
        if (!XmlRecord.isMatchHungry(target)) {
            return (false);
        }
        while (!target.isEmptyElement()) {
            if (!XmlRecord.isMatchHungry(target)) {
                break;
            }
        }
        if (!target.isEmptyElement()) {
            return (false);
        }
        return (true);
    }

    /**
     * Tests if elements contained in a Stack <code>stack</code>
     * is valid for the <code>XmlStar</code>.
     * This mehtod is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     * @return boolean
     */
    public static boolean isMatch(RStack stack) {
        Element element = stack.peekElement();
        if (element == null) {
            return (false);
        }
        return (isMatch(element));
    }

    /**
     * Tests if elements contained in a Stack <code>stack</code>
     * is valid for the <code>XmlStar</code>.
     * This method consumes the stack contents during matching operation.
     * This mehtod is supposed to be used internally
     * by the Relaxer system.
     *
     * @param stack
     * @return boolean
     */
    public static boolean isMatchHungry(RStack stack) {
        Element element = stack.peekElement();
        if (element == null) {
            return (false);
        }
        if (isMatch(element)) {
            stack.popElement();
            return (true);
        } else {
            return (false);
        }
    }
}
